"""Render the holding-page copy to SVG outlines in ABC Arizona Flare.

The font is licensed for desktop/print only (no @font-face, not allowed in a
public repo), so the text ships as static vector artwork instead. The OTFs live
outside the repo in ../../fonts-private. Re-run this after changing COPY.

  python3 tools/render_text.py   # needs: pip install uharfbuzz fonttools

Writes the <svg> snippets between the text:start / text:end markers in index.html.
"""
import re
from pathlib import Path

import uharfbuzz as hb
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen

ROOT = Path(__file__).resolve().parent.parent
FONT = ROOT.parent / "fonts-private" / "AnatlaArizonaFlare-Regular.otf"
HTML = ROOT / "index.html"

# (css class, text, {link word: href})
COPY = [
    ("headline", "WISER WORK", None),
    ("strap", "Developing Human Capacity", None),
    ("details", "The Founding Retreat, 9th – 11th February 2027", None),
    ("register", "Register your interest here",
     ("here", "mailto:dan@anatla.com?subject=The%20Founding%20Retreat")),
]
PAD = 20  # font units of breathing room round each line


def shape(blob_bytes, text):
    face = hb.Face(blob_bytes)
    font = hb.Font(face)
    buf = hb.Buffer()
    buf.add_str(text)
    buf.guess_segment_properties()
    hb.shape(font, buf, {"kern": True, "liga": True})
    return list(zip(buf.glyph_infos, buf.glyph_positions))


def main():
    data = FONT.read_bytes()
    tt = TTFont(FONT)
    glyph_set = tt.getGlyphSet()
    order = tt.getGlyphOrder()
    upm = tt["head"].unitsPerEm
    asc, desc = tt["OS/2"].sTypoAscender, tt["OS/2"].sTypoDescender
    post = tt["post"]
    ul_pos, ul_thick = post.underlinePosition, post.underlineThickness

    snippets = []
    for cls, text, link in COPY:
        glyphs = shape(data, text)
        x = 0
        pieces = []  # (cluster, x_start, x_end, path d)
        for info, pos in glyphs:
            name = order[info.codepoint]
            pen = SVGPathPen(glyph_set)
            # font y goes up; flip so SVG y goes down, baseline at y=0
            tpen = TransformPen(pen, (1, 0, 0, -1, x + pos.x_offset, -pos.y_offset))
            glyph_set[name].draw(tpen)
            pieces.append((info.cluster, x, x + pos.x_advance, pen.getCommands()))
            x += pos.x_advance
        width = x
        vb = f"{-PAD} {-asc - PAD} {width + 2 * PAD} {asc - desc + 2 * PAD}"

        if link:
            word, href = link
            start = text.index(word)
            end = start + len(word)
            # clusters are byte offsets in UTF-8; map char index -> byte offset
            b_start = len(text[:start].encode("utf-8"))
            b_end = len(text[:end].encode("utf-8"))
            plain = "".join(d for c, _, _, d in pieces if not (b_start <= c < b_end) and d)
            linked = [p for p in pieces if b_start <= p[0] < b_end]
            lx0, lx1 = linked[0][1], linked[-1][2]
            ld = "".join(d for _, _, _, d in linked if d)
            body = (
                f'<path d="{plain}"/>'
                f'<a href="{href}" aria-label="{word}: register your interest">'
                f'<path d="{ld}"/>'
                f'<rect class="ul" x="{lx0}" y="{-ul_pos}" width="{lx1 - lx0}" height="{ul_thick}"/>'
                f"</a>"
            )
        else:
            body = f'<path d="{"".join(d for _, _, _, d in pieces if d)}"/>'

        snippets.append(
            f'<svg class="t t--{cls}" viewBox="{vb}" role="img" aria-label="{text}" '
            f'fill="currentColor">{body}</svg>'
        )

    html = HTML.read_text()
    new = "<!-- text:start (generated by tools/render_text.py) -->\n      "
    new += "\n      ".join(snippets) + "\n      <!-- text:end -->"
    html, n = re.subn(r"<!-- text:start.*?<!-- text:end -->", new, html, flags=re.S)
    assert n == 1, "markers not found in index.html"
    HTML.write_text(html)
    print(f"wrote {len(snippets)} lines, {sum(len(s) for s in snippets)//1024} KB, upm={upm}")


if __name__ == "__main__":
    main()
